<?php

/**
 * @file
 * Contains ihorizons_next_article.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ihorizons_next_article_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ihorizons_next_article module.
    case 'help.page.ihorizons_next_article':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module provide functionality to load next url without refreshing the page.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_node().
 */
function ihorizons_next_article_preprocess_node(&$variables) {

  if (!empty($variables['node']->bundle())) {
    $variables['attributes']['class'][] = 'next-article';

    // Set next pages list
    $pages = [];

    $entity = \Drupal::entityQuery('node');
    $entity->condition('status', 1)
      ->condition('type', $variables['node']->bundle())
      ->condition('nid', $variables['node']->id(), '!=');
    $result = $entity->execute();

    if (!empty($result)) {
      foreach ($result as $node) {
        $node = \Drupal::service('entity_type.manager')->getStorage('node')->load($node);
        $pages[] = $node->toUrl()->setAbsolute()->toString();
      }
    }
    $variables['#attached']['library'][] = 'ihorizons_next_article/infinite_scroll';
    $variables['#attached']['drupalSettings']['ihorizons_next_article']['infiniteScroll']['next_articles'] = $pages;
  }
}

/**
 * Implements template_preprocess_region().
 */
function ihorizons_next_article_preprocess_block(&$variables) {

  if ($variables['plugin_id'] == 'system_main_block') {
    $variables['attributes']['class'][] = 'ihorizons-scroll';
  }
}
